DATASET:
    NAME: DES_GalaxyGalaxy_Lensing
    PARAMETERS:
        SIZE: 5000
        OUTDIR: DES_GalGal_Big

IMAGE:
    INPUT: configs/des/image.yaml
        
COSMOLOGY:
    PARAMETERS:
        H0: 70
        Om0: 0.3

SURVEY:
    INPUT: configs/des/survey.yaml


SPECIES:
    GALAXY_1:
        NAME: LENS
        LIGHT_PROFILE_1:
            NAME: SERSIC_ELLIPSE
            PARAMETERS:
                magnitude: -5.0

                center_x:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.03
                            maximum: 0.03
                center_y:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: -0.03
                            maximum: 0.03

                R_sersic:
                    DISTRIBUTION:
                        NAME: normal
                        PARAMETERS:
                            mean: 10
                            std: 2

                n_sersic:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 10.0
                e1: 0.2
                e2: -0.1

                            
        MASS_PROFILE_1:
            NAME: SIE 
            PARAMETERS:
                theta_E:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.5
                            maximum: 8.0
                e1: 0.1
                e2: -0.1
                center_x: 0.0
                center_y: 0.0
                
        SHEAR_PROFILE_1:
            NAME: SHEAR
            PARAMETERS:
                gamma1: 0.03
                gamma2: 0.01
                    
        SPECIAL:
            DES_COLOR: ['LIGHT_PROFILE_1']
            BRIGHTEN_EVERYTHING: ['LIGHT_PROFILE_1-6']
            MAKE_REDDER: ['LIGHT_PROFILE_1-2']

    GALAXY_2:
        NAME: SOURCE
        INPUT: configs/sersic_light_defaults.yaml

        SPECIAL:
            DES_COLOR: ['LIGHT_PROFILE_1']
            BRIGHTEN_EVERYTHING: ['LIGHT_PROFILE_1-4']
            MAKE_BLUEER: ['LIGHT_PROFILE_1-1']

    NOISE_1:
        NAME: POISSON_NOISE
        PARAMETERS:
            mean:
                DISTRIBUTION:
                    NAME: uniform
                    PARAMETERS:
                        minimum: 0.3
                        maximum: 0.5

        
GEOMETRY:

    CONFIGURATION_1:
        NAME: GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2
                            
        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.4
                            maximum: 0.6
                            
        NOISE_SOURCE_1: POISSON_NOISE

    CONFIGURATION_2:
        NAME: FAKE_GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            OBJECT_2: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

            NOISE_SOURCE_1: POISSON_NOISE

    CONFIGURATION_3:
        NAME: GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.4
                            maximum: 0.6

        NOISE_SOURCE_1: POISSON_NOISE

    CONFIGURATION_4:
        NAME: FAKE_GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            OBJECT_2: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

            NOISE_SOURCE_1: POISSON_NOISE

    CONFIGURATION_5:
        NAME: GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.4
                            maximum: 0.6

        NOISE_SOURCE_1: POISSON_NOISE


    CONFIGURATION_6:
        NAME: FAKE_GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            OBJECT_2: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

            NOISE_SOURCE_1: POISSON_NOISE

    CONFIGURATION_7:
        NAME: GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

        PLANE_2:
            OBJECT_1: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.4
                            maximum: 0.6

        NOISE_SOURCE_1: POISSON_NOISE


    CONFIGURATION_8:
        NAME: FAKE_GALAXY_GALAXY
        FRACTION: 1.0
        PLANE_1:
            OBJECT_1: LENS
            OBJECT_2: SOURCE
            PARAMETERS:
                REDSHIFT:
                    DISTRIBUTION:
                        NAME: uniform
                        PARAMETERS:
                            minimum: 0.05
                            maximum: 0.2

            NOISE_SOURCE_1: POISSON_NOISE