PARAMETERS:
    exposure_time:
        DISTRIBUTION:
            NAME: des_exposure_time
            PARAMETERS: None
    numPix: 100
    pixel_scale: 0.263
    psf_type: 'GAUSSIAN'
    read_noise: 7
    ccd_gain:
        DISTRIBUTION:
            NAME: des_ccd_gain
            PARAMETERS: None

